### ISSUE TITLE
Map old permalinks

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#119]
Pages should be mapped by perma links, the perma link is based on the title. If the title changes, a new perma link should be generated. In this case, the old perma link should continue to work. Therefore a mapping must exist.

**Comment by timoludwig** [comment]
With the versioning system of page translations, this is no longer an issue. As we create a new version whenever we change the slug of a page translation, we can just perform a simple database access and query for the translation with the given slug and return the most recent version of it.

**Comment by timoludwig** [comment]
I just noticed that I confused two things here: Yes, the slugs of the translations are stored automatically and we don't need any additional mapping for it, but in case we change the structure of the pages (e.g. move a page to another parent page), the permalink will change and we currently don't track that.
So I think that this _is_ a non-trivial issue to solve and revise my comment above.

**Comment by svenseeberg** [comment]
So what we need is two models: `PageTranslationPermalinkMap` and `EventTranslationPermalinkMap`, with each having an string attribute `permalink` and a foreign key to existing page or event translations. Right?

**Comment by timoludwig** [comment]
If we really need a permalink storage, yes. But I thought the current status of our Slack discussion was that we don't.
Since we store old slugs in the translation model (just in old revisions), the only reason we would need the storage is to track the hierarchy-changes of pages. But we can as well ignore them and just take the last URL parameter of the path as slug. The worst thing that can happen is that we map a permalink which never existed to an existing page (e.g. /augsburg/de-de/non-existent/welcome). But I see no downside for the real use case here and would prefer less models and a slimmer database structure.

**Comment by svenseeberg** [comment]
@timoludwig does mapping old slugs for page translations already work? If yes, we can close this issue.

**Comment by timoludwig** [comment]
Yes, you can always do:
```
old_revision = PageTranslation.objects.filter(slug="old-page-translation-slug").first()
new_revision = region.pages.get(id=old_revision.page.id).get_translation(old_revision.language.code)
```
or:
```
page = region.pages.filter(translations__slug="old-page-translation-slug").distinct().first()
```
