### ISSUE TITLE
Unify icon position in users table

### ISSUE THREAD

**Issue by Thomas125** [Integreat/cms-django#347]
In the users table, the icon indicating superuser is higher than the two others. They should all be at the same height.

**Comment by timoludwig** [comment]
I'm not sure if the `invalid` tag was intended to be used like this :sweat_smile: 
According to the [GitHub Help](https://help.github.com/en/github/managing-your-work-on-github/about-labels), it 
> Indicates that an issue or pull request is no longer relevant

So I assume that labels are meant to describe the GitHub issue itself, not the problem the issue is representing. I myself probably used them wrongly in the past :see_no_evil:

`/smart-alec-mode-off`
