### ISSUE TITLE
Translation: export XLIFF

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#37]
Enable exporting pages to XLIFF file.

Take translation state of pages into account. Unchanged pages or minor changes do not require translations.

**Comment by svenseeberg** [comment]
I'll create a Python module that we can use in Django for managing all translation stuff.

**Comment by timoludwig** [comment]
It would be perfect, if the direction of the xliff files follow the language tree of the specific site, in the moment we have default language into all other language, but ideally the root node of the langauge tree is the source language of its children, and so on. so in the example of a language tree DE -> EN -> AR we would have xliff files for DE to EN and for EN to AR. This is because sometimes translations from english to arabic are cheaper than from german to arabic.
