### ISSUE TITLE
Disable h1-tags in content

### ISSUE THREAD

**Issue by timoludwig** [Integreat/cms-django#516]
### Motivation

The apps use the `<h1>`-tags to display the title, so the content authors shouldn't use it in their content.

### Proposed Solution

Disable the creation of "Heading 1" in TinyMCE.

If it's not too much effort, we could also prevent the maual creation of `<h1>`-tags in the source code by validating the `text`/`description`-fields in the form's `clean()`-method.

**Comment by aitorres** [comment]
Hello! I could work on this issue and submit a PR in a day or two, if that's okay

**Comment by muditjain33** [comment]
Can I work on this issue?

**Comment by aitorres** [comment]
@timoludwig Hello! I was checking the code and found tinymce is being used across several forms. I have two questions, for now:

1. Should I disable the "Heading 1" style in all places tinymce is being used?
2. I would also like to do the extra `clean()` method validation, so I was wondering what the expected behavior would be: whether to raise a validation error if `<h1>` tags are present in the field, remove any pair of `<h1>...</h1>` and kept the inner text intact, or substitute any `<h1></h1>` tags with, say, `<h2>` equivalent tags.

**Comment by timoludwig** [comment]
>     1. Should I disable the "Heading 1" style in all places tinymce is being used?

Yes please. We wanted to simplify this by moving the tinymce to a separate file which is included from all content forms. For now, you can just copy + paste your solution to all tinymce scripts. (Or do the optimization yourself if you want to)

>     2. I would also like to do the extra `clean()` method validation, so I was wondering what the expected behavior would be: whether to raise a validation error if `<h1>` tags are present in the field, remove any pair of `<h1>...</h1>` and kept the inner text intact, or substitute any `<h1></h1>` tags with, say, `<h2>` equivalent tags.

Good question. I think I'd prefer the first option, so raise an error when the tags are present. Since this can also happen when you copy-paste a formatted text into the field, the error message should also be understandable for someone not knowing html.

**Comment by aitorres** [comment]
Thanks for the clarifications yesterday! I submitted a pull request, I think I got all of it (except for the two things I mention in the PR body). If there's any suggestions, errors or things I should change just let me know!

**Comment by aitorres** [comment]
Oh, and one more thing! (And sorry for the double reply). Yesterday night, DigitalOcean added a new requirement for repositories and pull requests to count towards the Hacktoberfest valid PR count, the information can be found here: https://hacktoberfest.digitalocean.com/hacktoberfest-update

It would be amazing if you could add the "hacktoberfest" tag/topic to the repository, at least for the duration of October, so that Pull Requests count for the event. Thanks again and I'm sorry to bother you!
